options:
  port:
    type: int
    default: 9402
    description: HTTP port
  self-signed-issuers:
    type: string
    description: |
      Self-signed issuers. See https://cert-manager.io/docs/configuration/selfsigned/
    default: |
      cert-manager-default:
  ca-issuers:
    type: string
    description: CA issuers. See https://cert-manager.io/docs/configuration/ca/
    default: '{}'
  acme-issuers:
    type: string
    description: ACME issuers. See https://cert-manager.io/docs/configuration/acme/
    default: '{}'
