name: MicroK8s Test

on:
  - push
  - pull_request

jobs:
  build:
    name: Deploy to microk8s
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install microk8s --classic
        sudo snap install charm --classic
        sudo snap install juju --classic
        sudo snap install juju-helpers --classic --channel edge
        sudo snap install juju-wait --classic

    - name: Deploy cert-manager
      run: |
        set -eux
        sudo usermod -a -G microk8s runner
        sudo microk8s.enable dns storage rbac
        sudo juju bootstrap microk8s uk8s
        sudo juju add-model cert-manager microk8s --config update-status-hook-interval=10s
        sudo juju bundle deploy --build
        sleep 10
        sudo microk8s.kubectl patch role -n cert-manager cert-manager-webhook-operator -p '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"cert-manager-webhook-operator"},"rules":[{"apiGroups":["*"],"resources":["*"],"verbs":["*"]}]}'
        sudo juju wait -wv -t 60

    - name: Test cert-manager
      run: ls -lath

    # Debug failures
    - name: Get pod statuses
      run: sudo microk8s.kubectl get all -A
      if: failure()
    - name: Get juju status
      run: sudo juju status
      if: failure()
    - name: Describe deployments
      run: sudo microk8s.kubectl describe deployments -A
      if: failure()
    - name: Describe replicasets
      run: sudo microk8s.kubectl describe replicasets -A
      if: failure()
    - name: Get cert-manager-controller operator logs
      run: sudo microk8s.kubectl logs -n cert-manager --tail 1000 -ljuju-operator=cert-manager-controller
      if: failure()
    - name: Get cert-manager-webhook operator logs
      run: sudo microk8s.kubectl logs -n cert-manager --tail 1000 -ljuju-operator=cert-manager-webhook
      if: failure()
    - name: Get cert-manager-controller logs
      run: sudo microk8s.kubectl logs -n cert-manager --tail 1000 -ljuju-app=cert-manager-controller
      if: failure()
    - name: Get cert-manager-webhook logs
      run: sudo microk8s.kubectl logs -n cert-manager --tail 1000 -ljuju-app=cert-manager-webhook
      if: failure()
    - name: Get snap logs
      run: sudo snap logs -n 300 microk8s
      if: failure()

